export const PRODUCTS = [
    { id: '1', name: 'Навушники', price: 2000, desc: 'Бездротові навушники з шумозаглушенням', image: 'https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg' },
    { id: '2', name: 'Колонка', price: 15000, desc: 'Потужний смартфон з гарною камерою', image: 'https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'  },
    { id: '3', name: 'Коврик', price: 2000, desc: 'Бездротові навушники з шумозаглушенням', image: 'https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'  },
    { id: '4', name: 'Чашка', price: 15000, desc: 'Потужний смартфон з гарною камерою', image: 'https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'  },
    { id: '5', name: 'Штани', price: 2000, desc: 'Бездротові навушники з шумозаглушенням', image: 'https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'  },
    { id: '6', name: 'Камера', price: 15000, desc: 'Потужний смартфон з гарною камерою', image: 'https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'  },
    { id: '7', name: 'Навушники', price: 2000, desc: 'Бездротові навушники з шумозаглушенням', image: 'https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'  },
];

